/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdministracaoRouteImport } from './routes/administracao'
import { Route as ArquivosCompartilhadosRouteImport } from './routes/arquivos-compartilhados'
import { Route as BibliotecaNegocioRouteImport } from './routes/biblioteca-negocio'
import { Route as ConteudoRouteImport } from './routes/conteudo'
import { Route as HubRouteImport } from './routes/hub'
import { Route as JornadaDeDesenvolvimentoRouteImport } from './routes/jornada-de-desenvolvimento'
import { Route as MeuAssessmentRouteImport } from './routes/meu-assessment'
import { Route as MinhasEstatisticasRouteImport } from './routes/minhas-estatisticas'
import { Route as PlanoDeAcaoRouteImport } from './routes/plano-de-acao'
import { Route as TreinamentosRouteImport } from './routes/treinamentos'
import { Route as BibliotecaConteudoContentIdRouteImport } from './routes/biblioteca/conteudo/$contentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracaoRoute = AdministracaoRouteImport.update({
  id: '/administracao',
  path: '/administracao',
  getParentRoute: () => rootRouteImport,
} as any)
const ArquivosCompartilhadosRoute = ArquivosCompartilhadosRouteImport.update({
  id: '/arquivos-compartilhados',
  path: '/arquivos-compartilhados',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaNegocioRoute = BibliotecaNegocioRouteImport.update({
  id: '/biblioteca-negocio',
  path: '/biblioteca-negocio',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoRoute = ConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const JornadaDeDesenvolvimentoRoute =
  JornadaDeDesenvolvimentoRouteImport.update({
    id: '/jornada-de-desenvolvimento',
    path: '/jornada-de-desenvolvimento',
    getParentRoute: () => rootRouteImport,
  } as any)
const MeuAssessmentRoute = MeuAssessmentRouteImport.update({
  id: '/meu-assessment',
  path: '/meu-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasEstatisticasRoute = MinhasEstatisticasRouteImport.update({
  id: '/minhas-estatisticas',
  path: '/minhas-estatisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoDeAcaoRoute = PlanoDeAcaoRouteImport.update({
  id: '/plano-de-acao',
  path: '/plano-de-acao',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinamentosRoute = TreinamentosRouteImport.update({
  id: '/treinamentos',
  path: '/treinamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaConteudoContentIdRoute =
  BibliotecaConteudoContentIdRouteImport.update({
    id: '/biblioteca/conteudo/$contentId',
    path: '/biblioteca/conteudo/$contentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/arquivos-compartilhados': typeof ArquivosCompartilhadosRoute
  '/biblioteca-negocio': typeof BibliotecaNegocioRoute
  '/conteudo': typeof ConteudoRoute
  '/hub': typeof HubRoute
  '/jornada-de-desenvolvimento': typeof JornadaDeDesenvolvimentoRoute
  '/meu-assessment': typeof MeuAssessmentRoute
  '/minhas-estatisticas': typeof MinhasEstatisticasRoute
  '/plano-de-acao': typeof PlanoDeAcaoRoute
  '/treinamentos': typeof TreinamentosRoute
  '/biblioteca/conteudo/$contentId': typeof BibliotecaConteudoContentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/arquivos-compartilhados': typeof ArquivosCompartilhadosRoute
  '/biblioteca-negocio': typeof BibliotecaNegocioRoute
  '/conteudo': typeof ConteudoRoute
  '/hub': typeof HubRoute
  '/jornada-de-desenvolvimento': typeof JornadaDeDesenvolvimentoRoute
  '/meu-assessment': typeof MeuAssessmentRoute
  '/minhas-estatisticas': typeof MinhasEstatisticasRoute
  '/plano-de-acao': typeof PlanoDeAcaoRoute
  '/treinamentos': typeof TreinamentosRoute
  '/biblioteca/conteudo/$contentId': typeof BibliotecaConteudoContentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/arquivos-compartilhados': typeof ArquivosCompartilhadosRoute
  '/biblioteca-negocio': typeof BibliotecaNegocioRoute
  '/conteudo': typeof ConteudoRoute
  '/hub': typeof HubRoute
  '/jornada-de-desenvolvimento': typeof JornadaDeDesenvolvimentoRoute
  '/meu-assessment': typeof MeuAssessmentRoute
  '/minhas-estatisticas': typeof MinhasEstatisticasRoute
  '/plano-de-acao': typeof PlanoDeAcaoRoute
  '/treinamentos': typeof TreinamentosRoute
  '/biblioteca/conteudo/$contentId': typeof BibliotecaConteudoContentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administracao'
    | '/arquivos-compartilhados'
    | '/biblioteca-negocio'
    | '/conteudo'
    | '/hub'
    | '/jornada-de-desenvolvimento'
    | '/meu-assessment'
    | '/minhas-estatisticas'
    | '/plano-de-acao'
    | '/treinamentos'
    | '/biblioteca/conteudo/$contentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administracao'
    | '/arquivos-compartilhados'
    | '/biblioteca-negocio'
    | '/conteudo'
    | '/hub'
    | '/jornada-de-desenvolvimento'
    | '/meu-assessment'
    | '/minhas-estatisticas'
    | '/plano-de-acao'
    | '/treinamentos'
    | '/biblioteca/conteudo/$contentId'
  id:
    | '__root__'
    | '/'
    | '/administracao'
    | '/arquivos-compartilhados'
    | '/biblioteca-negocio'
    | '/conteudo'
    | '/hub'
    | '/jornada-de-desenvolvimento'
    | '/meu-assessment'
    | '/minhas-estatisticas'
    | '/plano-de-acao'
    | '/treinamentos'
    | '/biblioteca/conteudo/$contentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministracaoRoute: typeof AdministracaoRoute
  ArquivosCompartilhadosRoute: typeof ArquivosCompartilhadosRoute
  BibliotecaNegocioRoute: typeof BibliotecaNegocioRoute
  ConteudoRoute: typeof ConteudoRoute
  HubRoute: typeof HubRoute
  JornadaDeDesenvolvimentoRoute: typeof JornadaDeDesenvolvimentoRoute
  MeuAssessmentRoute: typeof MeuAssessmentRoute
  MinhasEstatisticasRoute: typeof MinhasEstatisticasRoute
  PlanoDeAcaoRoute: typeof PlanoDeAcaoRoute
  TreinamentosRoute: typeof TreinamentosRoute
  BibliotecaConteudoContentIdRoute: typeof BibliotecaConteudoContentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracao': {
      id: '/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AdministracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arquivos-compartilhados': {
      id: '/arquivos-compartilhados'
      path: '/arquivos-compartilhados'
      fullPath: '/arquivos-compartilhados'
      preLoaderRoute: typeof ArquivosCompartilhadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca-negocio': {
      id: '/biblioteca-negocio'
      path: '/biblioteca-negocio'
      fullPath: '/biblioteca-negocio'
      preLoaderRoute: typeof BibliotecaNegocioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo': {
      id: '/conteudo'
      path: '/conteudo'
      fullPath: '/conteudo'
      preLoaderRoute: typeof ConteudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornada-de-desenvolvimento': {
      id: '/jornada-de-desenvolvimento'
      path: '/jornada-de-desenvolvimento'
      fullPath: '/jornada-de-desenvolvimento'
      preLoaderRoute: typeof JornadaDeDesenvolvimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-assessment': {
      id: '/meu-assessment'
      path: '/meu-assessment'
      fullPath: '/meu-assessment'
      preLoaderRoute: typeof MeuAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-estatisticas': {
      id: '/minhas-estatisticas'
      path: '/minhas-estatisticas'
      fullPath: '/minhas-estatisticas'
      preLoaderRoute: typeof MinhasEstatisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano-de-acao': {
      id: '/plano-de-acao'
      path: '/plano-de-acao'
      fullPath: '/plano-de-acao'
      preLoaderRoute: typeof PlanoDeAcaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinamentos': {
      id: '/treinamentos'
      path: '/treinamentos'
      fullPath: '/treinamentos'
      preLoaderRoute: typeof TreinamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/conteudo/$contentId': {
      id: '/biblioteca/conteudo/$contentId'
      path: '/biblioteca/conteudo/$contentId'
      fullPath: '/biblioteca/conteudo/$contentId'
      preLoaderRoute: typeof BibliotecaConteudoContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministracaoRoute: AdministracaoRoute,
  ArquivosCompartilhadosRoute: ArquivosCompartilhadosRoute,
  BibliotecaNegocioRoute: BibliotecaNegocioRoute,
  ConteudoRoute: ConteudoRoute,
  HubRoute: HubRoute,
  JornadaDeDesenvolvimentoRoute: JornadaDeDesenvolvimentoRoute,
  MeuAssessmentRoute: MeuAssessmentRoute,
  MinhasEstatisticasRoute: MinhasEstatisticasRoute,
  PlanoDeAcaoRoute: PlanoDeAcaoRoute,
  TreinamentosRoute: TreinamentosRoute,
  BibliotecaConteudoContentIdRoute: BibliotecaConteudoContentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
