/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdministracaoRouteImport } from './routes/administracao'
import { Route as HubRouteImport } from './routes/hub'
import { Route as MinhasEstatisticasRouteImport } from './routes/minhas-estatisticas'
import { Route as TreinamentosRouteImport } from './routes/treinamentos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracaoRoute = AdministracaoRouteImport.update({
  id: '/administracao',
  path: '/administracao',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasEstatisticasRoute = MinhasEstatisticasRouteImport.update({
  id: '/minhas-estatisticas',
  path: '/minhas-estatisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinamentosRoute = TreinamentosRouteImport.update({
  id: '/treinamentos',
  path: '/treinamentos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/hub': typeof HubRoute
  '/minhas-estatisticas': typeof MinhasEstatisticasRoute
  '/treinamentos': typeof TreinamentosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/hub': typeof HubRoute
  '/minhas-estatisticas': typeof MinhasEstatisticasRoute
  '/treinamentos': typeof TreinamentosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/hub': typeof HubRoute
  '/minhas-estatisticas': typeof MinhasEstatisticasRoute
  '/treinamentos': typeof TreinamentosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/administracao' | '/hub' | '/minhas-estatisticas' | '/treinamentos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/administracao' | '/hub' | '/minhas-estatisticas' | '/treinamentos'
  id:
    | '__root__'
    | '/'
    | '/administracao'
    | '/hub'
    | '/minhas-estatisticas'
    | '/treinamentos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministracaoRoute: typeof AdministracaoRoute
  HubRoute: typeof HubRoute
  MinhasEstatisticasRoute: typeof MinhasEstatisticasRoute
  TreinamentosRoute: typeof TreinamentosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracao': {
      id: '/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AdministracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-estatisticas': {
      id: '/minhas-estatisticas'
      path: '/minhas-estatisticas'
      fullPath: '/minhas-estatisticas'
      preLoaderRoute: typeof MinhasEstatisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinamentos': {
      id: '/treinamentos'
      path: '/treinamentos'
      fullPath: '/treinamentos'
      preLoaderRoute: typeof TreinamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministracaoRoute: AdministracaoRoute,
  HubRoute: HubRoute,
  MinhasEstatisticasRoute: MinhasEstatisticasRoute,
  TreinamentosRoute: TreinamentosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
